
---
date: 2024-02-06
title: 'Daily Update – Feb 06, 2024'
format: 
    html:
      toc: false
title-block-banner: true
execute:
    echo: false
    warning: false
    message: false
---
'Meta Stock Surge, 2024 Market Crash?, Political Power, Trump vs Biden &amp; Black Media ft Roland Martin; HYPE MIC MONDAYS | Live From Atlanta 🔥; President Kagame Africa must STOP begging, POWERFUL Lecture; When Black Power Gets Whitewashed | Ron Karenga &amp; Kwanzaa Breakdown Clip; CAN YOU BE A PAN-AFRICANIST AND VOTE REPUBLICAN ?'

```{r}

library(tidyverse)
googlesheets4::gs4_deauth()
sheet <- googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/1bJIUEOh8yUg46dREnE_bXlha9K35nqkFk85CyQYn2eY/edit#gid=932148422',
                                   sheet =  'YouTube Channels')

videos_tbl <- read_csv('videos_tbl.csv') |> 
  mutate(embeds = embeds |> 
           str_replace_all('480', '100%') |> 
           str_replace_all('270', '400'))

```

```{r}
#| echo: false

# A list of summaries:

 
videos_joined <- videos_tbl |> 
    left_join(sheet, by = join_by(channelId == id)) |> 
    select(publishedAt,title, description, embeds, 
           channelId, Category) |> 
    filter(publishedAt >= lubridate::today()-1)

videos <- videos_joined |>  
    split(videos_joined$Category) 
    

headings <- names(videos)
#videos
```

## Today's Videos

::: panel-tabset
```{r, results='asis'}
#| warning: false


for (i in seq_along(videos)) {
    cat("# ",headings[i],"\n")
    current_df <- videos[[i]]
  
    
    for (j in seq_along(current_df$embeds)) {
        current_value <- current_df$embeds[j]
        
        current_title <- current_df$title[j]
        cat("### ",current_title,"\n")
        cat(current_value)
        cat("\n")
        cat("\n") 
         
         
         
 }
}
```
:::
