project:
  type: website

website:
  title: "afromation"
  favicon: assets/images/afromation_favicon.png
  navbar:
    background: dark
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/afromation.io/
      - icon: twitter
        href: https://twitter.com/afromation_io
  
format:
  html:
    theme:
      dark: assets/css/custom.scss
    css: assets/css/styles.css
    background-color: 'black'

editor: visual

