project:
  type: website
  render:
    - "*.qmd"
    - "!generator"

website:
  title: "afromation"
  site-url: "https://afromation.io"
  favicon: assets/images/afromation_favicon.png
  navbar:
    background: dark
    right:
      - blog.qmd
      - articles.qmd
      - icon: instagram
        href: https://www.instagram.com/afromation.io/
      - icon: twitter
        href: https://twitter.com/afromation_io

format:
  html:
    theme:
      # dark: assets/css/custom.scss
      light: [flatly, assets/css/custom.scss]
    css: assets/css/styles.css
    background-color: "white"
    toc: true
    include-after-body: subscribe.html

editor: visual