project:
  type: website

website:
  title: "afromation"
  site-url: "https://drum.afromation.io"
  favicon: assets/images/afromation_favicon.png
  navbar:
    background: dark
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/afromation.io/
      - icon: twitter
        href: https://twitter.com/afromation_io

format:
  html:
    theme:
      dark: assets/css/custom.scss
    css: assets/css/styles.css
    background-color: "black"
    toc: true
    include-after-body: subscribe.html

editor: visual

listing:
  feed:
    categories: [education, culture, history]