---
title: "HOME"
page-layout: full
title-block-banner: true
format:
  html:
    css: assets/css/feed_header.css
    
listing:
  contents: stories
  id: stories
  sort: "date desc"
  type: grid
  categories: false
  sort-ui: false
  filter-ui: false

execute:
  echo: false
  warning: false
  message: false
---
# [Stories]{.updates}
::: {#stories}
:::

```{r}

library(tidyverse)

videos_tbl <- read_csv('posts/2024-05-26/videos_tbl.csv') |> 
  mutate(embeds = embeds |> 
           str_replace_all('480', '100%') |> 
           str_replace_all('height="270"', ''))


```

```{r}
#| echo: false

videos_joined <- videos_tbl |> 
    select(publishedAt,title, description, embeds, 
           channelId, channelTitle, category) |> 
    filter(publishedAt >= lubridate::ymd('2024-05-26')-1)


videos <- videos_joined |>  
    split(videos_joined$category) 
    

headings <- names(videos)
```

# [Updates – May 26, 2024]{.updates}

```{r, results='asis'}
#| warning: false

for (i in seq_along(videos)) {
    cat("## ", headings[i], "\n")
    current_df <- videos[[i]]
    
    cat("::: {#listing-listing .quarto-listing .quarto-listing-container-grid}", '\n')
    cat('::: {.list .grid .quarto-listing-cols-3}', '\n')
    
    for (j in seq_along(current_df$embeds)) {
      if (!is.na(current_df$embeds[j])) {  # Check if the embed is not empty
        cat("::: g-col-1", '\n')
        cat("::: {.quarto-grid-item .card .h-100 .card-left}", '\n')
        cat('::: {.listing-item-img-placeholder .card-img-top style="height: 150px;"}', '\n')
        cat(current_df$embeds[j],'\n')
        cat(":::",'\n')
        cat("::: {.card-body .post-contents}",'\n')
        cat('<h5 class="card-title listing-title">', current_df$title[j],'</h5> \n')
        cat("::: {.card-attribution .card-text-small .justify} ",'\n')
        cat("::: listing-author ",'\n')
        cat(current_df$channelTitle[j],'\n')
        cat(":::",'\n')
        cat('\n')
        cat("::: listing-date ",'\n')
        cat(format(current_df$publishedAt[j], "%b %d"),'\n')
        cat(":::",'\n')
        cat(":::",'\n')
        cat(":::",'\n')
        cat(":::",'\n')
        cat(":::",'\n')
      }
  }
    cat(":::",'\n')
    cat(":::",'\n')
}

```

