---
execute: 
  echo: false
  warning: false
  message: false
---

```{r}

library(tidyverse)

googlesheets4::gs4_deauth()
sheet <- googlesheets4::read_sheet('https://docs.google.com/spreadsheets/d/1bJIUEOh8yUg46dREnE_bXlha9K35nqkFk85CyQYn2eY/edit#gid=932148422',
                                   sheet =  'YouTube Channels')

# sheet

```

```{r}
videos_tbl <- read_csv('videos_tbl.csv') |> 
  mutate(embeds = embeds |> str_replace_all('480', '100%'))

#videos_tbl
```

Code to make a bunch of example models.

```{r}
#| echo: false

# A list of summaries:


# channels <-  sheet |> 
#     select(Creator, id, Category, Example) |> 
#     mutate(iframe= glue::glue('<iframe width="560" height="315" src="https://www.youtube.com/embed/{Example}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>')) |> 
#     split(sheet$Category ) 
#     
 
videos_joined <- videos_tbl |> 
    left_join(sheet, by = join_by(channelId == id)) |> 
    select(publishedAt,title, description, embeds, 
           channelId, Category) |> 
    filter(publishedAt >= lubridate::today()-1)

videos <- videos_joined |>  
    split(videos_joined$Category) 
    

headings <- names(videos)
#videos
```

## Today's Videos

::: panel-tabset
```{r, results='asis'}
#| warning: false


for (i in seq_along(videos)) {
    cat("# ",headings[i],"\n")
    current_df <- videos[[i]]
  
    
    for (j in seq_along(current_df$embeds)) {
        current_value <- current_df$embeds[j]
        
        current_title <- current_df$title[j]
        cat("### ",current_title,"\n")
        cat(current_value)
        cat("\n")
        cat("\n") 
         
         
         
  }
}
```
:::
