---
date: 2024-02-27
title: 'Daily Update – Feb 27, 2024'
author: 'Afromation Digital'
format: 
    html:
      toc: false
title-block-banner: true
execute:
    echo: false
    warning: false
    message: false
---
'ICJ holds Emergency Hearings on Legal Consequences of Israel’s Genocide in Palestine; NVIDIA Unstoppable Stock Rise, The Best Company of The Next Decade, &amp; Racial Wealth Gap Truths; Vijay Prashad On Congo #Shorts; HYPE MIC MONDAYS | Live From Atlanta 🔥; Black Hebrews Have No Seat At The Table When It Comes To Their &quot;Promised Land&quot;'

```{r}

library(tidyverse)

videos_tbl <- read_csv('videos_tbl.csv') |> 
  mutate(embeds = embeds |> 
           str_replace_all('480', '100%') |> 
           str_replace_all('270', '50%'))


```

```{r}
#| echo: false

videos_joined <- videos_tbl |> 
    select(publishedAt,title, description, embeds, 
           channelId, category) |> 
    filter(publishedAt >= lubridate::ymd('2024-02-27')-1)

videos <- videos_joined |>  
    split(videos_joined$category) 
    

headings <- names(videos)

```

## Today's Videos

::: panel-tabset
```{r, results='asis'}
#| warning: false


for (i in seq_along(videos)) {
    cat("# ",headings[i],"\n")
    current_df <- videos[[i]]
  
    
    for (j in seq_along(current_df$embeds)) {
        current_value <- current_df$embeds[j]
        
        current_title <- current_df$title[j]
        cat("### ",current_title,"\n")
        cat(current_value)
        cat("\n")
        cat("\n") 
         
         
         
 }
}
```
:::
