on:
  workflow_dispatch:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.0"

      - name: Install dependencies
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install renv Dependencies
        uses: r-lib/actions/setup-renv@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.KEY }}
          known_hosts: "placeholder"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Rsync over SSH
        run: rsync -avz --delete ./_site/ ${{secrets.USERNAME}}@${{secrets.HOST}}:/var/www/drum/public_html/
